// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cpp.proto
// Protobuf C++ Version: 6.33.4

#include "cpp.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Vec3f::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_{0},
        y_{0},
        z_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Vec3f::Vec3f(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Vec3f_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Vec3fDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Vec3fDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Vec3fDefaultTypeInternal() {}
  union {
    Vec3f _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Vec3fDefaultTypeInternal _Vec3f_default_instance_;

inline constexpr Payload::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        typename__(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR Payload::Payload(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Payload_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadDefaultTypeInternal() {}
  union {
    Payload _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadDefaultTypeInternal _Payload_default_instance_;

inline constexpr CUDAExtent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        width_{::int64_t{0}},
        height_{::int64_t{0}},
        depth_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR CUDAExtent::CUDAExtent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CUDAExtent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CUDAExtentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CUDAExtentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CUDAExtentDefaultTypeInternal() {}
  union {
    CUDAExtent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CUDAExtentDefaultTypeInternal _CUDAExtent_default_instance_;

inline constexpr CUDAChannelFormatDesc::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        x_{0u},
        y_{0u},
        z_{0u},
        w_{0u},
        f_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR CUDAChannelFormatDesc::CUDAChannelFormatDesc(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CUDAChannelFormatDesc_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CUDAChannelFormatDescDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CUDAChannelFormatDescDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CUDAChannelFormatDescDefaultTypeInternal() {}
  union {
    CUDAChannelFormatDesc _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CUDAChannelFormatDescDefaultTypeInternal _CUDAChannelFormatDesc_default_instance_;

inline constexpr ByteBuffers::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        data_{} {}

template <typename>
PROTOBUF_CONSTEXPR ByteBuffers::ByteBuffers(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ByteBuffers_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ByteBuffersDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ByteBuffersDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ByteBuffersDefaultTypeInternal() {}
  union {
    ByteBuffers _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ByteBuffersDefaultTypeInternal _ByteBuffers_default_instance_;

inline constexpr CUDAArrayObject::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        handle_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        formatdesc_{nullptr},
        extent_{nullptr},
        bpp_{::uint64_t{0u}},
        pitch_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR CUDAArrayObject::CUDAArrayObject(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CUDAArrayObject_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CUDAArrayObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CUDAArrayObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CUDAArrayObjectDefaultTypeInternal() {}
  union {
    CUDAArrayObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CUDAArrayObjectDefaultTypeInternal _CUDAArrayObject_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_cpp_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_cpp_2eproto = nullptr;
const ::uint32_t
    TableStruct_cpp_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ByteBuffers, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ByteBuffers, _impl_.data_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Payload, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Payload, _impl_.typename__),
        PROTOBUF_FIELD_OFFSET(::Payload, _impl_.data_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::Vec3f, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::Vec3f, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::Vec3f, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::Vec3f, _impl_.z_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CUDAExtent, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CUDAExtent, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::CUDAExtent, _impl_.height_),
        PROTOBUF_FIELD_OFFSET(::CUDAExtent, _impl_.depth_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CUDAChannelFormatDesc, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CUDAChannelFormatDesc, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::CUDAChannelFormatDesc, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::CUDAChannelFormatDesc, _impl_.z_),
        PROTOBUF_FIELD_OFFSET(::CUDAChannelFormatDesc, _impl_.w_),
        PROTOBUF_FIELD_OFFSET(::CUDAChannelFormatDesc, _impl_.f_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CUDAArrayObject, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CUDAArrayObject, _impl_.handle_),
        PROTOBUF_FIELD_OFFSET(::CUDAArrayObject, _impl_.formatdesc_),
        PROTOBUF_FIELD_OFFSET(::CUDAArrayObject, _impl_.bpp_),
        PROTOBUF_FIELD_OFFSET(::CUDAArrayObject, _impl_.pitch_),
        PROTOBUF_FIELD_OFFSET(::CUDAArrayObject, _impl_.extent_),
        0,
        1,
        3,
        4,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::ByteBuffers)},
        {5, sizeof(::Payload)},
        {12, sizeof(::Vec3f)},
        {21, sizeof(::CUDAExtent)},
        {30, sizeof(::CUDAChannelFormatDesc)},
        {43, sizeof(::CUDAArrayObject)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_ByteBuffers_default_instance_._instance,
    &::_Payload_default_instance_._instance,
    &::_Vec3f_default_instance_._instance,
    &::_CUDAExtent_default_instance_._instance,
    &::_CUDAChannelFormatDesc_default_instance_._instance,
    &::_CUDAArrayObject_default_instance_._instance,
};
const char descriptor_table_protodef_cpp_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tcpp.proto\"\033\n\013ByteBuffers\022\014\n\004data\030\001 \003(\014"
    "\")\n\007Payload\022\020\n\010typename\030\001 \001(\t\022\014\n\004data\030\002 "
    "\001(\014\"(\n\005Vec3f\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030"
    "\003 \001(\002\":\n\nCUDAExtent\022\r\n\005width\030\001 \001(\003\022\016\n\006he"
    "ight\030\002 \001(\003\022\r\n\005depth\030\003 \001(\003\"N\n\025CUDAChannel"
    "FormatDesc\022\t\n\001x\030\001 \001(\r\022\t\n\001y\030\002 \001(\r\022\t\n\001z\030\003 "
    "\001(\r\022\t\n\001w\030\004 \001(\r\022\t\n\001f\030\005 \001(\r\"\206\001\n\017CUDAArrayO"
    "bject\022\016\n\006handle\030\001 \001(\014\022*\n\nformatDesc\030\002 \001("
    "\0132\026.CUDAChannelFormatDesc\022\013\n\003bpp\030\003 \001(\004\022\r"
    "\n\005pitch\030\004 \001(\004\022\033\n\006extent\030\005 \001(\0132\013.CUDAExte"
    "nt"
};
static ::absl::once_flag descriptor_table_cpp_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cpp_2eproto = {
    false,
    false,
    402,
    descriptor_table_protodef_cpp_2eproto,
    "cpp.proto",
    &descriptor_table_cpp_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_cpp_2eproto::offsets,
    file_level_enum_descriptors_cpp_2eproto,
    file_level_service_descriptors_cpp_2eproto,
};
// ===================================================================

class ByteBuffers::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ByteBuffers>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ByteBuffers, _impl_._has_bits_);
};

ByteBuffers::ByteBuffers(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ByteBuffers_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ByteBuffers)
}
PROTOBUF_NDEBUG_INLINE ByteBuffers::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::ByteBuffers& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        data_{visibility, arena, from.data_} {}

ByteBuffers::ByteBuffers(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ByteBuffers& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ByteBuffers_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ByteBuffers* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ByteBuffers)
}
PROTOBUF_NDEBUG_INLINE ByteBuffers::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        data_{visibility, arena} {}

inline void ByteBuffers::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ByteBuffers::~ByteBuffers() {
  // @@protoc_insertion_point(destructor:ByteBuffers)
  SharedDtor(*this);
}
inline void ByteBuffers::SharedDtor(MessageLite& self) {
  ByteBuffers& this_ = static_cast<ByteBuffers&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ByteBuffers::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ByteBuffers(arena);
}
constexpr auto ByteBuffers::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ByteBuffers, _impl_.data_) +
          decltype(ByteBuffers::_impl_.data_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ByteBuffers), alignof(ByteBuffers), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ByteBuffers::PlacementNew_,
                                 sizeof(ByteBuffers),
                                 alignof(ByteBuffers));
  }
}
constexpr auto ByteBuffers::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ByteBuffers_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ByteBuffers::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ByteBuffers>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ByteBuffers::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ByteBuffers>(), &ByteBuffers::ByteSizeLong,
              &ByteBuffers::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ByteBuffers, _impl_._cached_size_),
          false,
      },
      &ByteBuffers::kDescriptorMethods,
      &descriptor_table_cpp_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ByteBuffers_class_data_ =
        ByteBuffers::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ByteBuffers::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ByteBuffers_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ByteBuffers_class_data_.tc_table);
  return ByteBuffers_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
ByteBuffers::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ByteBuffers, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ByteBuffers_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ByteBuffers>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated bytes data = 1;
    {::_pbi::TcParser::FastBR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(ByteBuffers, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated bytes data = 1;
    {PROTOBUF_FIELD_OFFSET(ByteBuffers, _impl_.data_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ByteBuffers::Clear() {
// @@protoc_insertion_point(message_clear_start:ByteBuffers)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.data_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ByteBuffers::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ByteBuffers& this_ = static_cast<const ByteBuffers&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ByteBuffers::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ByteBuffers& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ByteBuffers)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated bytes data = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_data_size(); i < n; ++i) {
      const auto& s = this_._internal_data().Get(i);
      target = stream->WriteBytes(1, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ByteBuffers)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ByteBuffers::ByteSizeLong(const MessageLite& base) {
  const ByteBuffers& this_ = static_cast<const ByteBuffers&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ByteBuffers::ByteSizeLong() const {
  const ByteBuffers& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ByteBuffers)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated bytes data = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_data().size());
      for (int i = 0, n = this_._internal_data().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
            this_._internal_data().Get(i));
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ByteBuffers::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ByteBuffers*>(&to_msg);
  auto& from = static_cast<const ByteBuffers&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:ByteBuffers)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_data()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_data());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ByteBuffers::CopyFrom(const ByteBuffers& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ByteBuffers)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ByteBuffers::InternalSwap(ByteBuffers* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::google::protobuf::Metadata ByteBuffers::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Payload::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Payload>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Payload, _impl_._has_bits_);
};

Payload::Payload(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Payload_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Payload)
}
PROTOBUF_NDEBUG_INLINE Payload::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::Payload& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        typename__(arena, from.typename__),
        data_(arena, from.data_) {}

Payload::Payload(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Payload& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Payload_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Payload* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Payload)
}
PROTOBUF_NDEBUG_INLINE Payload::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        typename__(arena),
        data_(arena) {}

inline void Payload::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Payload::~Payload() {
  // @@protoc_insertion_point(destructor:Payload)
  SharedDtor(*this);
}
inline void Payload::SharedDtor(MessageLite& self) {
  Payload& this_ = static_cast<Payload&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.typename__.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Payload::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Payload(arena);
}
constexpr auto Payload::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Payload),
                                            alignof(Payload));
}
constexpr auto Payload::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Payload_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Payload::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Payload>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Payload::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Payload>(), &Payload::ByteSizeLong,
              &Payload::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Payload, _impl_._cached_size_),
          false,
      },
      &Payload::kDescriptorMethods,
      &descriptor_table_cpp_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Payload_class_data_ =
        Payload::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Payload::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Payload_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Payload_class_data_.tc_table);
  return Payload_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
Payload::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Payload, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Payload_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Payload>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bytes data = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(Payload, _impl_.data_)}},
    // optional string typename = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Payload, _impl_.typename__)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string typename = 1;
    {PROTOBUF_FIELD_OFFSET(Payload, _impl_.typename__), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bytes data = 2;
    {PROTOBUF_FIELD_OFFSET(Payload, _impl_.data_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Payload::Clear() {
// @@protoc_insertion_point(message_clear_start:Payload)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.typename__.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Payload::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Payload& this_ = static_cast<const Payload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Payload::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Payload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Payload)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string typename = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_typename_();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional bytes data = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_data();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Payload)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Payload::ByteSizeLong(const MessageLite& base) {
  const Payload& this_ = static_cast<const Payload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Payload::ByteSizeLong() const {
  const Payload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Payload)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional string typename = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_typename_());
    }
    // optional bytes data = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_data());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Payload::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Payload*>(&to_msg);
  auto& from = static_cast<const Payload&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Payload)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_typename_(from._internal_typename_());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_data(from._internal_data());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Payload::CopyFrom(const Payload& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Payload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Payload::InternalSwap(Payload* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.typename__, &other->_impl_.typename__, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
}

::google::protobuf::Metadata Payload::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Vec3f::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Vec3f>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Vec3f, _impl_._has_bits_);
};

Vec3f::Vec3f(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Vec3f_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Vec3f)
}
Vec3f::Vec3f(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Vec3f& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Vec3f_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Vec3f::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Vec3f::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
Vec3f::~Vec3f() {
  // @@protoc_insertion_point(destructor:Vec3f)
  SharedDtor(*this);
}
inline void Vec3f::SharedDtor(MessageLite& self) {
  Vec3f& this_ = static_cast<Vec3f&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Vec3f::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Vec3f(arena);
}
constexpr auto Vec3f::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Vec3f),
                                            alignof(Vec3f));
}
constexpr auto Vec3f::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Vec3f_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Vec3f::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Vec3f>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Vec3f::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Vec3f>(), &Vec3f::ByteSizeLong,
              &Vec3f::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Vec3f, _impl_._cached_size_),
          false,
      },
      &Vec3f::kDescriptorMethods,
      &descriptor_table_cpp_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Vec3f_class_data_ =
        Vec3f::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Vec3f::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Vec3f_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Vec3f_class_data_.tc_table);
  return Vec3f_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
Vec3f::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Vec3f, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Vec3f_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Vec3f>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0,
      PROTOBUF_FIELD_OFFSET(Vec3f, _impl_.x_)}},
    // optional float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0,
      PROTOBUF_FIELD_OFFSET(Vec3f, _impl_.y_)}},
    // optional float z = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0,
      PROTOBUF_FIELD_OFFSET(Vec3f, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional float x = 1;
    {PROTOBUF_FIELD_OFFSET(Vec3f, _impl_.x_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float y = 2;
    {PROTOBUF_FIELD_OFFSET(Vec3f, _impl_.y_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float z = 3;
    {PROTOBUF_FIELD_OFFSET(Vec3f, _impl_.z_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Vec3f::Clear() {
// @@protoc_insertion_point(message_clear_start:Vec3f)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.x_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.z_) -
        reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Vec3f::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Vec3f& this_ = static_cast<const Vec3f&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Vec3f::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Vec3f& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:Vec3f)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional float x = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this_._internal_x(), target);
  }

  // optional float y = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_y(), target);
  }

  // optional float z = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this_._internal_z(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Vec3f)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Vec3f::ByteSizeLong(const MessageLite& base) {
  const Vec3f& this_ = static_cast<const Vec3f&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Vec3f::ByteSizeLong() const {
  const Vec3f& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:Vec3f)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x00000007U & cached_has_bits) * 5;
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Vec3f::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Vec3f*>(&to_msg);
  auto& from = static_cast<const Vec3f&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:Vec3f)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.x_ = from._impl_.x_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.y_ = from._impl_.y_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.z_ = from._impl_.z_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Vec3f::CopyFrom(const Vec3f& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:Vec3f)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Vec3f::InternalSwap(Vec3f* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Vec3f, _impl_.z_)
      + sizeof(Vec3f::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Vec3f, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Vec3f::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CUDAExtent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CUDAExtent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_._has_bits_);
};

CUDAExtent::CUDAExtent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CUDAExtent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CUDAExtent)
}
CUDAExtent::CUDAExtent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CUDAExtent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CUDAExtent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CUDAExtent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CUDAExtent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, width_),
           0,
           offsetof(Impl_, depth_) -
               offsetof(Impl_, width_) +
               sizeof(Impl_::depth_));
}
CUDAExtent::~CUDAExtent() {
  // @@protoc_insertion_point(destructor:CUDAExtent)
  SharedDtor(*this);
}
inline void CUDAExtent::SharedDtor(MessageLite& self) {
  CUDAExtent& this_ = static_cast<CUDAExtent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CUDAExtent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CUDAExtent(arena);
}
constexpr auto CUDAExtent::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CUDAExtent),
                                            alignof(CUDAExtent));
}
constexpr auto CUDAExtent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CUDAExtent_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CUDAExtent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CUDAExtent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CUDAExtent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CUDAExtent>(), &CUDAExtent::ByteSizeLong,
              &CUDAExtent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_._cached_size_),
          false,
      },
      &CUDAExtent::kDescriptorMethods,
      &descriptor_table_cpp_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CUDAExtent_class_data_ =
        CUDAExtent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CUDAExtent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CUDAExtent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CUDAExtent_class_data_.tc_table);
  return CUDAExtent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
CUDAExtent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CUDAExtent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CUDAExtent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int64 width = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CUDAExtent, _impl_.width_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_.width_)}},
    // optional int64 height = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CUDAExtent, _impl_.height_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_.height_)}},
    // optional int64 depth = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CUDAExtent, _impl_.depth_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_.depth_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int64 width = 1;
    {PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_.width_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 height = 2;
    {PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_.height_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 depth = 3;
    {PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_.depth_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CUDAExtent::Clear() {
// @@protoc_insertion_point(message_clear_start:CUDAExtent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    ::memset(&_impl_.width_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.depth_) -
        reinterpret_cast<char*>(&_impl_.width_)) + sizeof(_impl_.depth_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CUDAExtent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CUDAExtent& this_ = static_cast<const CUDAExtent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CUDAExtent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CUDAExtent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CUDAExtent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 width = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
            stream, this_._internal_width(), target);
  }

  // optional int64 height = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
            stream, this_._internal_height(), target);
  }

  // optional int64 depth = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
            stream, this_._internal_depth(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUDAExtent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CUDAExtent::ByteSizeLong(const MessageLite& base) {
  const CUDAExtent& this_ = static_cast<const CUDAExtent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CUDAExtent::ByteSizeLong() const {
  const CUDAExtent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CUDAExtent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional int64 width = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_width());
    }
    // optional int64 height = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_height());
    }
    // optional int64 depth = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_depth());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CUDAExtent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CUDAExtent*>(&to_msg);
  auto& from = static_cast<const CUDAExtent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CUDAExtent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.width_ = from._impl_.width_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.height_ = from._impl_.height_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.depth_ = from._impl_.depth_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CUDAExtent::CopyFrom(const CUDAExtent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CUDAExtent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CUDAExtent::InternalSwap(CUDAExtent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_.depth_)
      + sizeof(CUDAExtent::_impl_.depth_)
      - PROTOBUF_FIELD_OFFSET(CUDAExtent, _impl_.width_)>(
          reinterpret_cast<char*>(&_impl_.width_),
          reinterpret_cast<char*>(&other->_impl_.width_));
}

::google::protobuf::Metadata CUDAExtent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CUDAChannelFormatDesc::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CUDAChannelFormatDesc>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_._has_bits_);
};

CUDAChannelFormatDesc::CUDAChannelFormatDesc(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CUDAChannelFormatDesc_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CUDAChannelFormatDesc)
}
CUDAChannelFormatDesc::CUDAChannelFormatDesc(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CUDAChannelFormatDesc& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CUDAChannelFormatDesc_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CUDAChannelFormatDesc::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CUDAChannelFormatDesc::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, f_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::f_));
}
CUDAChannelFormatDesc::~CUDAChannelFormatDesc() {
  // @@protoc_insertion_point(destructor:CUDAChannelFormatDesc)
  SharedDtor(*this);
}
inline void CUDAChannelFormatDesc::SharedDtor(MessageLite& self) {
  CUDAChannelFormatDesc& this_ = static_cast<CUDAChannelFormatDesc&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CUDAChannelFormatDesc::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CUDAChannelFormatDesc(arena);
}
constexpr auto CUDAChannelFormatDesc::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CUDAChannelFormatDesc),
                                            alignof(CUDAChannelFormatDesc));
}
constexpr auto CUDAChannelFormatDesc::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CUDAChannelFormatDesc_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CUDAChannelFormatDesc::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CUDAChannelFormatDesc>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CUDAChannelFormatDesc::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CUDAChannelFormatDesc>(), &CUDAChannelFormatDesc::ByteSizeLong,
              &CUDAChannelFormatDesc::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_._cached_size_),
          false,
      },
      &CUDAChannelFormatDesc::kDescriptorMethods,
      &descriptor_table_cpp_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CUDAChannelFormatDesc_class_data_ =
        CUDAChannelFormatDesc::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CUDAChannelFormatDesc::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CUDAChannelFormatDesc_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CUDAChannelFormatDesc_class_data_.tc_table);
  return CUDAChannelFormatDesc_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
CUDAChannelFormatDesc::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CUDAChannelFormatDesc_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CUDAChannelFormatDesc>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 x = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CUDAChannelFormatDesc, _impl_.x_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.x_)}},
    // optional uint32 y = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CUDAChannelFormatDesc, _impl_.y_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.y_)}},
    // optional uint32 z = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CUDAChannelFormatDesc, _impl_.z_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.z_)}},
    // optional uint32 w = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CUDAChannelFormatDesc, _impl_.w_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.w_)}},
    // optional uint32 f = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CUDAChannelFormatDesc, _impl_.f_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.f_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 x = 1;
    {PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.x_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 y = 2;
    {PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.y_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 z = 3;
    {PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.z_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 w = 4;
    {PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.w_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 f = 5;
    {PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.f_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CUDAChannelFormatDesc::Clear() {
// @@protoc_insertion_point(message_clear_start:CUDAChannelFormatDesc)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    ::memset(&_impl_.x_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.f_) -
        reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.f_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CUDAChannelFormatDesc::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CUDAChannelFormatDesc& this_ = static_cast<const CUDAChannelFormatDesc&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CUDAChannelFormatDesc::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CUDAChannelFormatDesc& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CUDAChannelFormatDesc)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 x = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_x(), target);
  }

  // optional uint32 y = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_y(), target);
  }

  // optional uint32 z = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_z(), target);
  }

  // optional uint32 w = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this_._internal_w(), target);
  }

  // optional uint32 f = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this_._internal_f(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUDAChannelFormatDesc)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CUDAChannelFormatDesc::ByteSizeLong(const MessageLite& base) {
  const CUDAChannelFormatDesc& this_ = static_cast<const CUDAChannelFormatDesc&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CUDAChannelFormatDesc::ByteSizeLong() const {
  const CUDAChannelFormatDesc& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CUDAChannelFormatDesc)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // optional uint32 x = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_x());
    }
    // optional uint32 y = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_y());
    }
    // optional uint32 z = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_z());
    }
    // optional uint32 w = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_w());
    }
    // optional uint32 f = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_f());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CUDAChannelFormatDesc::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CUDAChannelFormatDesc*>(&to_msg);
  auto& from = static_cast<const CUDAChannelFormatDesc&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CUDAChannelFormatDesc)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_impl_.x_ = from._impl_.x_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.y_ = from._impl_.y_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.z_ = from._impl_.z_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.w_ = from._impl_.w_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.f_ = from._impl_.f_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CUDAChannelFormatDesc::CopyFrom(const CUDAChannelFormatDesc& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CUDAChannelFormatDesc)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CUDAChannelFormatDesc::InternalSwap(CUDAChannelFormatDesc* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.f_)
      + sizeof(CUDAChannelFormatDesc::_impl_.f_)
      - PROTOBUF_FIELD_OFFSET(CUDAChannelFormatDesc, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata CUDAChannelFormatDesc::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CUDAArrayObject::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CUDAArrayObject>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_._has_bits_);
};

CUDAArrayObject::CUDAArrayObject(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CUDAArrayObject_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CUDAArrayObject)
}
PROTOBUF_NDEBUG_INLINE CUDAArrayObject::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CUDAArrayObject& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        handle_(arena, from.handle_) {}

CUDAArrayObject::CUDAArrayObject(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CUDAArrayObject& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CUDAArrayObject_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CUDAArrayObject* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.formatdesc_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.formatdesc_)
                : nullptr;
  _impl_.extent_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.extent_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, bpp_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, bpp_),
           offsetof(Impl_, pitch_) -
               offsetof(Impl_, bpp_) +
               sizeof(Impl_::pitch_));

  // @@protoc_insertion_point(copy_constructor:CUDAArrayObject)
}
PROTOBUF_NDEBUG_INLINE CUDAArrayObject::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        handle_(arena) {}

inline void CUDAArrayObject::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, formatdesc_),
           0,
           offsetof(Impl_, pitch_) -
               offsetof(Impl_, formatdesc_) +
               sizeof(Impl_::pitch_));
}
CUDAArrayObject::~CUDAArrayObject() {
  // @@protoc_insertion_point(destructor:CUDAArrayObject)
  SharedDtor(*this);
}
inline void CUDAArrayObject::SharedDtor(MessageLite& self) {
  CUDAArrayObject& this_ = static_cast<CUDAArrayObject&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.handle_.Destroy();
  delete this_._impl_.formatdesc_;
  delete this_._impl_.extent_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CUDAArrayObject::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CUDAArrayObject(arena);
}
constexpr auto CUDAArrayObject::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CUDAArrayObject),
                                            alignof(CUDAArrayObject));
}
constexpr auto CUDAArrayObject::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CUDAArrayObject_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CUDAArrayObject::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CUDAArrayObject>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CUDAArrayObject::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CUDAArrayObject>(), &CUDAArrayObject::ByteSizeLong,
              &CUDAArrayObject::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_._cached_size_),
          false,
      },
      &CUDAArrayObject::kDescriptorMethods,
      &descriptor_table_cpp_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CUDAArrayObject_class_data_ =
        CUDAArrayObject::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CUDAArrayObject::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CUDAArrayObject_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CUDAArrayObject_class_data_.tc_table);
  return CUDAArrayObject_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 2, 0, 2>
CUDAArrayObject::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CUDAArrayObject_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CUDAArrayObject>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional bytes handle = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.handle_)}},
    // optional .CUDAChannelFormatDesc formatDesc = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.formatdesc_)}},
    // optional uint64 bpp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CUDAArrayObject, _impl_.bpp_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.bpp_)}},
    // optional uint64 pitch = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CUDAArrayObject, _impl_.pitch_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.pitch_)}},
    // optional .CUDAExtent extent = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 2, 1,
      PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.extent_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bytes handle = 1;
    {PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.handle_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional .CUDAChannelFormatDesc formatDesc = 2;
    {PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.formatdesc_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional uint64 bpp = 3;
    {PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.bpp_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 pitch = 4;
    {PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.pitch_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional .CUDAExtent extent = 5;
    {PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.extent_), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::CUDAChannelFormatDesc>()},
      {::_pbi::TcParser::GetTable<::CUDAExtent>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void CUDAArrayObject::Clear() {
// @@protoc_insertion_point(message_clear_start:CUDAArrayObject)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.handle_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.formatdesc_ != nullptr);
      _impl_.formatdesc_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.extent_ != nullptr);
      _impl_.extent_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000018U)) {
    ::memset(&_impl_.bpp_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.pitch_) -
        reinterpret_cast<char*>(&_impl_.bpp_)) + sizeof(_impl_.pitch_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CUDAArrayObject::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CUDAArrayObject& this_ = static_cast<const CUDAArrayObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CUDAArrayObject::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CUDAArrayObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CUDAArrayObject)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bytes handle = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_handle();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // optional .CUDAChannelFormatDesc formatDesc = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.formatdesc_, this_._impl_.formatdesc_->GetCachedSize(), target,
        stream);
  }

  // optional uint64 bpp = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this_._internal_bpp(), target);
  }

  // optional uint64 pitch = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        4, this_._internal_pitch(), target);
  }

  // optional .CUDAExtent extent = 5;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.extent_, this_._impl_.extent_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CUDAArrayObject)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CUDAArrayObject::ByteSizeLong(const MessageLite& base) {
  const CUDAArrayObject& this_ = static_cast<const CUDAArrayObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CUDAArrayObject::ByteSizeLong() const {
  const CUDAArrayObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CUDAArrayObject)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // optional bytes handle = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_handle());
    }
    // optional .CUDAChannelFormatDesc formatDesc = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.formatdesc_);
    }
    // optional .CUDAExtent extent = 5;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.extent_);
    }
    // optional uint64 bpp = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_bpp());
    }
    // optional uint64 pitch = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_pitch());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CUDAArrayObject::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CUDAArrayObject*>(&to_msg);
  auto& from = static_cast<const CUDAArrayObject&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:CUDAArrayObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_handle(from._internal_handle());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.formatdesc_ != nullptr);
      if (_this->_impl_.formatdesc_ == nullptr) {
        _this->_impl_.formatdesc_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.formatdesc_);
      } else {
        _this->_impl_.formatdesc_->MergeFrom(*from._impl_.formatdesc_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.extent_ != nullptr);
      if (_this->_impl_.extent_ == nullptr) {
        _this->_impl_.extent_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.extent_);
      } else {
        _this->_impl_.extent_->MergeFrom(*from._impl_.extent_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.bpp_ = from._impl_.bpp_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.pitch_ = from._impl_.pitch_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CUDAArrayObject::CopyFrom(const CUDAArrayObject& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CUDAArrayObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CUDAArrayObject::InternalSwap(CUDAArrayObject* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.handle_, &other->_impl_.handle_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.pitch_)
      + sizeof(CUDAArrayObject::_impl_.pitch_)
      - PROTOBUF_FIELD_OFFSET(CUDAArrayObject, _impl_.formatdesc_)>(
          reinterpret_cast<char*>(&_impl_.formatdesc_),
          reinterpret_cast<char*>(&other->_impl_.formatdesc_));
}

::google::protobuf::Metadata CUDAArrayObject::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_cpp_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
