

message ByteBuffers {
repeated bytes data = 1;
}

message Payload {
optional string typename = 1;
optional bytes data = 2;
}

message Vec3f {
optional float x = 1;
optional float y = 2;
optional float z = 3;
}

message CUDAExtent {
optional int64 width = 1;
optional int64 height = 2;
optional int64 depth = 3;
}

message CUDAChannelFormatDesc {
optional uint32 x = 1;
optional uint32 y = 2;
optional uint32 z = 3;
optional uint32 w = 4;
optional uint32 f = 5;
}

message CUDAArrayObject {
optional bytes handle = 1;
optional CUDAChannelFormatDesc formatDesc = 2;
optional uint64 bpp = 3;
optional uint64 pitch = 4;
optional CUDAExtent extent = 5;
}