// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cpp.proto
// Protobuf C++ Version: 6.33.4

#ifndef cpp_2eproto_2epb_2eh
#define cpp_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cpp_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cpp_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_cpp_2eproto;
}  // extern "C"
class ByteBuffers;
struct ByteBuffersDefaultTypeInternal;
extern ByteBuffersDefaultTypeInternal _ByteBuffers_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ByteBuffers_class_data_;
class CUDAArrayObject;
struct CUDAArrayObjectDefaultTypeInternal;
extern CUDAArrayObjectDefaultTypeInternal _CUDAArrayObject_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CUDAArrayObject_class_data_;
class CUDAChannelFormatDesc;
struct CUDAChannelFormatDescDefaultTypeInternal;
extern CUDAChannelFormatDescDefaultTypeInternal _CUDAChannelFormatDesc_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CUDAChannelFormatDesc_class_data_;
class CUDAExtent;
struct CUDAExtentDefaultTypeInternal;
extern CUDAExtentDefaultTypeInternal _CUDAExtent_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CUDAExtent_class_data_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Payload_class_data_;
class Vec3f;
struct Vec3fDefaultTypeInternal;
extern Vec3fDefaultTypeInternal _Vec3f_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Vec3f_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Vec3f final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Vec3f) */ {
 public:
  inline Vec3f() : Vec3f(nullptr) {}
  ~Vec3f() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Vec3f* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Vec3f));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Vec3f(::google::protobuf::internal::ConstantInitialized);

  inline Vec3f(const Vec3f& from) : Vec3f(nullptr, from) {}
  inline Vec3f(Vec3f&& from) noexcept
      : Vec3f(nullptr, ::std::move(from)) {}
  inline Vec3f& operator=(const Vec3f& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec3f& operator=(Vec3f&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec3f& default_instance() {
    return *reinterpret_cast<const Vec3f*>(
        &_Vec3f_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Vec3f& a, Vec3f& b) { a.Swap(&b); }
  inline void Swap(Vec3f* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec3f* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec3f* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Vec3f>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Vec3f& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Vec3f& from) { Vec3f::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Vec3f* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Vec3f"; }

  explicit Vec3f(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Vec3f(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Vec3f& from);
  Vec3f(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Vec3f&& from) noexcept
      : Vec3f(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // optional float x = 1;
  bool has_x() const;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // optional float y = 2;
  bool has_y() const;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // optional float z = 3;
  bool has_z() const;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:Vec3f)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Vec3f& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float x_;
    float y_;
    float z_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cpp_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Vec3f_class_data_;
// -------------------------------------------------------------------

class Payload final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Payload* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Payload));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Payload(::google::protobuf::internal::ConstantInitialized);

  inline Payload(const Payload& from) : Payload(nullptr, from) {}
  inline Payload(Payload&& from) noexcept
      : Payload(nullptr, ::std::move(from)) {}
  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Payload& default_instance() {
    return *reinterpret_cast<const Payload*>(
        &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Payload& a, Payload& b) { a.Swap(&b); }
  inline void Swap(Payload* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Payload>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Payload& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Payload& from) { Payload::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Payload* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Payload"; }

  explicit Payload(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Payload(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Payload& from);
  Payload(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Payload&& from) noexcept
      : Payload(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypenameFieldNumber = 1,
    kDataFieldNumber = 2,
  };
  // optional string typename = 1;
  bool has_typename_() const;
  void clear_typename_() ;
  const ::std::string& typename_() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_typename_(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_typename_();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_typename_();
  void set_allocated_typename_(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_typename_() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_typename_(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_typename_();

  public:
  // optional bytes data = 2;
  bool has_data() const;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:Payload)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Payload& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr typename__;
    ::google::protobuf::internal::ArenaStringPtr data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cpp_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Payload_class_data_;
// -------------------------------------------------------------------

class CUDAExtent final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CUDAExtent) */ {
 public:
  inline CUDAExtent() : CUDAExtent(nullptr) {}
  ~CUDAExtent() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CUDAExtent* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CUDAExtent));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CUDAExtent(::google::protobuf::internal::ConstantInitialized);

  inline CUDAExtent(const CUDAExtent& from) : CUDAExtent(nullptr, from) {}
  inline CUDAExtent(CUDAExtent&& from) noexcept
      : CUDAExtent(nullptr, ::std::move(from)) {}
  inline CUDAExtent& operator=(const CUDAExtent& from) {
    CopyFrom(from);
    return *this;
  }
  inline CUDAExtent& operator=(CUDAExtent&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CUDAExtent& default_instance() {
    return *reinterpret_cast<const CUDAExtent*>(
        &_CUDAExtent_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(CUDAExtent& a, CUDAExtent& b) { a.Swap(&b); }
  inline void Swap(CUDAExtent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CUDAExtent* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CUDAExtent* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CUDAExtent>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CUDAExtent& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CUDAExtent& from) { CUDAExtent::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CUDAExtent* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CUDAExtent"; }

  explicit CUDAExtent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CUDAExtent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CUDAExtent& from);
  CUDAExtent(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CUDAExtent&& from) noexcept
      : CUDAExtent(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
    kDepthFieldNumber = 3,
  };
  // optional int64 width = 1;
  bool has_width() const;
  void clear_width() ;
  ::int64_t width() const;
  void set_width(::int64_t value);

  private:
  ::int64_t _internal_width() const;
  void _internal_set_width(::int64_t value);

  public:
  // optional int64 height = 2;
  bool has_height() const;
  void clear_height() ;
  ::int64_t height() const;
  void set_height(::int64_t value);

  private:
  ::int64_t _internal_height() const;
  void _internal_set_height(::int64_t value);

  public:
  // optional int64 depth = 3;
  bool has_depth() const;
  void clear_depth() ;
  ::int64_t depth() const;
  void set_depth(::int64_t value);

  private:
  ::int64_t _internal_depth() const;
  void _internal_set_depth(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:CUDAExtent)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CUDAExtent& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t width_;
    ::int64_t height_;
    ::int64_t depth_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cpp_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CUDAExtent_class_data_;
// -------------------------------------------------------------------

class CUDAChannelFormatDesc final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CUDAChannelFormatDesc) */ {
 public:
  inline CUDAChannelFormatDesc() : CUDAChannelFormatDesc(nullptr) {}
  ~CUDAChannelFormatDesc() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CUDAChannelFormatDesc* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CUDAChannelFormatDesc));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CUDAChannelFormatDesc(::google::protobuf::internal::ConstantInitialized);

  inline CUDAChannelFormatDesc(const CUDAChannelFormatDesc& from) : CUDAChannelFormatDesc(nullptr, from) {}
  inline CUDAChannelFormatDesc(CUDAChannelFormatDesc&& from) noexcept
      : CUDAChannelFormatDesc(nullptr, ::std::move(from)) {}
  inline CUDAChannelFormatDesc& operator=(const CUDAChannelFormatDesc& from) {
    CopyFrom(from);
    return *this;
  }
  inline CUDAChannelFormatDesc& operator=(CUDAChannelFormatDesc&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CUDAChannelFormatDesc& default_instance() {
    return *reinterpret_cast<const CUDAChannelFormatDesc*>(
        &_CUDAChannelFormatDesc_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(CUDAChannelFormatDesc& a, CUDAChannelFormatDesc& b) { a.Swap(&b); }
  inline void Swap(CUDAChannelFormatDesc* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CUDAChannelFormatDesc* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CUDAChannelFormatDesc* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CUDAChannelFormatDesc>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CUDAChannelFormatDesc& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CUDAChannelFormatDesc& from) { CUDAChannelFormatDesc::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CUDAChannelFormatDesc* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CUDAChannelFormatDesc"; }

  explicit CUDAChannelFormatDesc(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CUDAChannelFormatDesc(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CUDAChannelFormatDesc& from);
  CUDAChannelFormatDesc(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CUDAChannelFormatDesc&& from) noexcept
      : CUDAChannelFormatDesc(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kWFieldNumber = 4,
    kFFieldNumber = 5,
  };
  // optional uint32 x = 1;
  bool has_x() const;
  void clear_x() ;
  ::uint32_t x() const;
  void set_x(::uint32_t value);

  private:
  ::uint32_t _internal_x() const;
  void _internal_set_x(::uint32_t value);

  public:
  // optional uint32 y = 2;
  bool has_y() const;
  void clear_y() ;
  ::uint32_t y() const;
  void set_y(::uint32_t value);

  private:
  ::uint32_t _internal_y() const;
  void _internal_set_y(::uint32_t value);

  public:
  // optional uint32 z = 3;
  bool has_z() const;
  void clear_z() ;
  ::uint32_t z() const;
  void set_z(::uint32_t value);

  private:
  ::uint32_t _internal_z() const;
  void _internal_set_z(::uint32_t value);

  public:
  // optional uint32 w = 4;
  bool has_w() const;
  void clear_w() ;
  ::uint32_t w() const;
  void set_w(::uint32_t value);

  private:
  ::uint32_t _internal_w() const;
  void _internal_set_w(::uint32_t value);

  public:
  // optional uint32 f = 5;
  bool has_f() const;
  void clear_f() ;
  ::uint32_t f() const;
  void set_f(::uint32_t value);

  private:
  ::uint32_t _internal_f() const;
  void _internal_set_f(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CUDAChannelFormatDesc)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CUDAChannelFormatDesc& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t x_;
    ::uint32_t y_;
    ::uint32_t z_;
    ::uint32_t w_;
    ::uint32_t f_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cpp_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CUDAChannelFormatDesc_class_data_;
// -------------------------------------------------------------------

class ByteBuffers final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ByteBuffers) */ {
 public:
  inline ByteBuffers() : ByteBuffers(nullptr) {}
  ~ByteBuffers() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ByteBuffers* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ByteBuffers));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ByteBuffers(::google::protobuf::internal::ConstantInitialized);

  inline ByteBuffers(const ByteBuffers& from) : ByteBuffers(nullptr, from) {}
  inline ByteBuffers(ByteBuffers&& from) noexcept
      : ByteBuffers(nullptr, ::std::move(from)) {}
  inline ByteBuffers& operator=(const ByteBuffers& from) {
    CopyFrom(from);
    return *this;
  }
  inline ByteBuffers& operator=(ByteBuffers&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ByteBuffers& default_instance() {
    return *reinterpret_cast<const ByteBuffers*>(
        &_ByteBuffers_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ByteBuffers& a, ByteBuffers& b) { a.Swap(&b); }
  inline void Swap(ByteBuffers* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ByteBuffers* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ByteBuffers* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ByteBuffers>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ByteBuffers& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ByteBuffers& from) { ByteBuffers::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ByteBuffers* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ByteBuffers"; }

  explicit ByteBuffers(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ByteBuffers(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ByteBuffers& from);
  ByteBuffers(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ByteBuffers&& from) noexcept
      : ByteBuffers(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated bytes data = 1;
  int data_size() const;
  private:
  int _internal_data_size() const;

  public:
  void clear_data() ;
  const ::std::string& data(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_data(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_data();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_data(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& data() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_data();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_data() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:ByteBuffers)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ByteBuffers& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cpp_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ByteBuffers_class_data_;
// -------------------------------------------------------------------

class CUDAArrayObject final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CUDAArrayObject) */ {
 public:
  inline CUDAArrayObject() : CUDAArrayObject(nullptr) {}
  ~CUDAArrayObject() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CUDAArrayObject* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CUDAArrayObject));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CUDAArrayObject(::google::protobuf::internal::ConstantInitialized);

  inline CUDAArrayObject(const CUDAArrayObject& from) : CUDAArrayObject(nullptr, from) {}
  inline CUDAArrayObject(CUDAArrayObject&& from) noexcept
      : CUDAArrayObject(nullptr, ::std::move(from)) {}
  inline CUDAArrayObject& operator=(const CUDAArrayObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline CUDAArrayObject& operator=(CUDAArrayObject&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CUDAArrayObject& default_instance() {
    return *reinterpret_cast<const CUDAArrayObject*>(
        &_CUDAArrayObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(CUDAArrayObject& a, CUDAArrayObject& b) { a.Swap(&b); }
  inline void Swap(CUDAArrayObject* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CUDAArrayObject* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CUDAArrayObject* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CUDAArrayObject>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CUDAArrayObject& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CUDAArrayObject& from) { CUDAArrayObject::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CUDAArrayObject* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CUDAArrayObject"; }

  explicit CUDAArrayObject(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CUDAArrayObject(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CUDAArrayObject& from);
  CUDAArrayObject(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CUDAArrayObject&& from) noexcept
      : CUDAArrayObject(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHandleFieldNumber = 1,
    kFormatDescFieldNumber = 2,
    kExtentFieldNumber = 5,
    kBppFieldNumber = 3,
    kPitchFieldNumber = 4,
  };
  // optional bytes handle = 1;
  bool has_handle() const;
  void clear_handle() ;
  const ::std::string& handle() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_handle(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_handle();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_handle();
  void set_allocated_handle(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_handle() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_handle(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_handle();

  public:
  // optional .CUDAChannelFormatDesc formatDesc = 2;
  bool has_formatdesc() const;
  void clear_formatdesc() ;
  const ::CUDAChannelFormatDesc& formatdesc() const;
  [[nodiscard]] ::CUDAChannelFormatDesc* PROTOBUF_NULLABLE release_formatdesc();
  ::CUDAChannelFormatDesc* PROTOBUF_NONNULL mutable_formatdesc();
  void set_allocated_formatdesc(::CUDAChannelFormatDesc* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_formatdesc(::CUDAChannelFormatDesc* PROTOBUF_NULLABLE value);
  ::CUDAChannelFormatDesc* PROTOBUF_NULLABLE unsafe_arena_release_formatdesc();

  private:
  const ::CUDAChannelFormatDesc& _internal_formatdesc() const;
  ::CUDAChannelFormatDesc* PROTOBUF_NONNULL _internal_mutable_formatdesc();

  public:
  // optional .CUDAExtent extent = 5;
  bool has_extent() const;
  void clear_extent() ;
  const ::CUDAExtent& extent() const;
  [[nodiscard]] ::CUDAExtent* PROTOBUF_NULLABLE release_extent();
  ::CUDAExtent* PROTOBUF_NONNULL mutable_extent();
  void set_allocated_extent(::CUDAExtent* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_extent(::CUDAExtent* PROTOBUF_NULLABLE value);
  ::CUDAExtent* PROTOBUF_NULLABLE unsafe_arena_release_extent();

  private:
  const ::CUDAExtent& _internal_extent() const;
  ::CUDAExtent* PROTOBUF_NONNULL _internal_mutable_extent();

  public:
  // optional uint64 bpp = 3;
  bool has_bpp() const;
  void clear_bpp() ;
  ::uint64_t bpp() const;
  void set_bpp(::uint64_t value);

  private:
  ::uint64_t _internal_bpp() const;
  void _internal_set_bpp(::uint64_t value);

  public:
  // optional uint64 pitch = 4;
  bool has_pitch() const;
  void clear_pitch() ;
  ::uint64_t pitch() const;
  void set_pitch(::uint64_t value);

  private:
  ::uint64_t _internal_pitch() const;
  void _internal_set_pitch(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:CUDAArrayObject)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CUDAArrayObject& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr handle_;
    ::CUDAChannelFormatDesc* PROTOBUF_NULLABLE formatdesc_;
    ::CUDAExtent* PROTOBUF_NULLABLE extent_;
    ::uint64_t bpp_;
    ::uint64_t pitch_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cpp_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CUDAArrayObject_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ByteBuffers

// repeated bytes data = 1;
inline int ByteBuffers::_internal_data_size() const {
  return _internal_data().size();
}
inline int ByteBuffers::data_size() const {
  return _internal_data_size();
}
inline void ByteBuffers::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL ByteBuffers::add_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_data()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:ByteBuffers.data)
  return _s;
}
inline const ::std::string& ByteBuffers::data(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ByteBuffers.data)
  return _internal_data().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL ByteBuffers::mutable_data(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ByteBuffers.data)
  return _internal_mutable_data()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ByteBuffers::set_data(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_data()->Mutable(index), ::std::forward<Arg_>(value),
                        args... , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_set:ByteBuffers.data)
}
template <typename Arg_, typename... Args_>
inline void ByteBuffers::add_data(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_data(), ::std::forward<Arg_>(value),
      args... , ::google::protobuf::internal::BytesTag{});
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:ByteBuffers.data)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& ByteBuffers::data()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ByteBuffers.data)
  return _internal_data();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ByteBuffers::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:ByteBuffers.data)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_data();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
ByteBuffers::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ByteBuffers::_internal_mutable_data() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.data_;
}

// -------------------------------------------------------------------

// Payload

// optional string typename = 1;
inline bool Payload::has_typename_() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void Payload::clear_typename_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typename__.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Payload::typename_() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Payload.typename)
  return _internal_typename_();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Payload::set_typename_(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.typename__.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Payload.typename)
}
inline ::std::string* PROTOBUF_NONNULL Payload::mutable_typename_()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_typename_();
  // @@protoc_insertion_point(field_mutable:Payload.typename)
  return _s;
}
inline const ::std::string& Payload::_internal_typename_() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.typename__.Get();
}
inline void Payload::_internal_set_typename_(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typename__.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Payload::_internal_mutable_typename_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.typename__.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Payload::release_typename_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Payload.typename)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.typename__.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.typename__.Set("", GetArena());
  }
  return released;
}
inline void Payload::set_allocated_typename_(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.typename__.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.typename__.IsDefault()) {
    _impl_.typename__.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Payload.typename)
}

// optional bytes data = 2;
inline bool Payload::has_data() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Payload::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Payload::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Payload.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Payload::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Payload.data)
}
inline ::std::string* PROTOBUF_NONNULL Payload::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Payload.data)
  return _s;
}
inline const ::std::string& Payload::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void Payload::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Payload::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Payload::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Payload.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void Payload::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Payload.data)
}

// -------------------------------------------------------------------

// Vec3f

// optional float x = 1;
inline bool Vec3f::has_x() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void Vec3f::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline float Vec3f::x() const {
  // @@protoc_insertion_point(field_get:Vec3f.x)
  return _internal_x();
}
inline void Vec3f::set_x(float value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Vec3f.x)
}
inline float Vec3f::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Vec3f::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// optional float y = 2;
inline bool Vec3f::has_y() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Vec3f::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline float Vec3f::y() const {
  // @@protoc_insertion_point(field_get:Vec3f.y)
  return _internal_y();
}
inline void Vec3f::set_y(float value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Vec3f.y)
}
inline float Vec3f::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Vec3f::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// optional float z = 3;
inline bool Vec3f::has_z() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Vec3f::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline float Vec3f::z() const {
  // @@protoc_insertion_point(field_get:Vec3f.z)
  return _internal_z();
}
inline void Vec3f::set_z(float value) {
  _internal_set_z(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Vec3f.z)
}
inline float Vec3f::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void Vec3f::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// CUDAExtent

// optional int64 width = 1;
inline bool CUDAExtent::has_width() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CUDAExtent::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int64_t CUDAExtent::width() const {
  // @@protoc_insertion_point(field_get:CUDAExtent.width)
  return _internal_width();
}
inline void CUDAExtent::set_width(::int64_t value) {
  _internal_set_width(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CUDAExtent.width)
}
inline ::int64_t CUDAExtent::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void CUDAExtent::_internal_set_width(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// optional int64 height = 2;
inline bool CUDAExtent::has_height() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CUDAExtent::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int64_t CUDAExtent::height() const {
  // @@protoc_insertion_point(field_get:CUDAExtent.height)
  return _internal_height();
}
inline void CUDAExtent::set_height(::int64_t value) {
  _internal_set_height(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CUDAExtent.height)
}
inline ::int64_t CUDAExtent::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void CUDAExtent::_internal_set_height(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// optional int64 depth = 3;
inline bool CUDAExtent::has_depth() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CUDAExtent::clear_depth() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.depth_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int64_t CUDAExtent::depth() const {
  // @@protoc_insertion_point(field_get:CUDAExtent.depth)
  return _internal_depth();
}
inline void CUDAExtent::set_depth(::int64_t value) {
  _internal_set_depth(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:CUDAExtent.depth)
}
inline ::int64_t CUDAExtent::_internal_depth() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.depth_;
}
inline void CUDAExtent::_internal_set_depth(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.depth_ = value;
}

// -------------------------------------------------------------------

// CUDAChannelFormatDesc

// optional uint32 x = 1;
inline bool CUDAChannelFormatDesc::has_x() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CUDAChannelFormatDesc::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t CUDAChannelFormatDesc::x() const {
  // @@protoc_insertion_point(field_get:CUDAChannelFormatDesc.x)
  return _internal_x();
}
inline void CUDAChannelFormatDesc::set_x(::uint32_t value) {
  _internal_set_x(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CUDAChannelFormatDesc.x)
}
inline ::uint32_t CUDAChannelFormatDesc::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void CUDAChannelFormatDesc::_internal_set_x(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// optional uint32 y = 2;
inline bool CUDAChannelFormatDesc::has_y() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CUDAChannelFormatDesc::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t CUDAChannelFormatDesc::y() const {
  // @@protoc_insertion_point(field_get:CUDAChannelFormatDesc.y)
  return _internal_y();
}
inline void CUDAChannelFormatDesc::set_y(::uint32_t value) {
  _internal_set_y(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CUDAChannelFormatDesc.y)
}
inline ::uint32_t CUDAChannelFormatDesc::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void CUDAChannelFormatDesc::_internal_set_y(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// optional uint32 z = 3;
inline bool CUDAChannelFormatDesc::has_z() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CUDAChannelFormatDesc::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t CUDAChannelFormatDesc::z() const {
  // @@protoc_insertion_point(field_get:CUDAChannelFormatDesc.z)
  return _internal_z();
}
inline void CUDAChannelFormatDesc::set_z(::uint32_t value) {
  _internal_set_z(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:CUDAChannelFormatDesc.z)
}
inline ::uint32_t CUDAChannelFormatDesc::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void CUDAChannelFormatDesc::_internal_set_z(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// optional uint32 w = 4;
inline bool CUDAChannelFormatDesc::has_w() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CUDAChannelFormatDesc::clear_w() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.w_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t CUDAChannelFormatDesc::w() const {
  // @@protoc_insertion_point(field_get:CUDAChannelFormatDesc.w)
  return _internal_w();
}
inline void CUDAChannelFormatDesc::set_w(::uint32_t value) {
  _internal_set_w(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:CUDAChannelFormatDesc.w)
}
inline ::uint32_t CUDAChannelFormatDesc::_internal_w() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.w_;
}
inline void CUDAChannelFormatDesc::_internal_set_w(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.w_ = value;
}

// optional uint32 f = 5;
inline bool CUDAChannelFormatDesc::has_f() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void CUDAChannelFormatDesc::clear_f() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.f_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t CUDAChannelFormatDesc::f() const {
  // @@protoc_insertion_point(field_get:CUDAChannelFormatDesc.f)
  return _internal_f();
}
inline void CUDAChannelFormatDesc::set_f(::uint32_t value) {
  _internal_set_f(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:CUDAChannelFormatDesc.f)
}
inline ::uint32_t CUDAChannelFormatDesc::_internal_f() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.f_;
}
inline void CUDAChannelFormatDesc::_internal_set_f(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.f_ = value;
}

// -------------------------------------------------------------------

// CUDAArrayObject

// optional bytes handle = 1;
inline bool CUDAArrayObject::has_handle() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CUDAArrayObject::clear_handle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.handle_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CUDAArrayObject::handle() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CUDAArrayObject.handle)
  return _internal_handle();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CUDAArrayObject::set_handle(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.handle_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CUDAArrayObject.handle)
}
inline ::std::string* PROTOBUF_NONNULL CUDAArrayObject::mutable_handle()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_handle();
  // @@protoc_insertion_point(field_mutable:CUDAArrayObject.handle)
  return _s;
}
inline const ::std::string& CUDAArrayObject::_internal_handle() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.handle_.Get();
}
inline void CUDAArrayObject::_internal_set_handle(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.handle_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CUDAArrayObject::_internal_mutable_handle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.handle_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CUDAArrayObject::release_handle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CUDAArrayObject.handle)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.handle_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.handle_.Set("", GetArena());
  }
  return released;
}
inline void CUDAArrayObject::set_allocated_handle(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.handle_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.handle_.IsDefault()) {
    _impl_.handle_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CUDAArrayObject.handle)
}

// optional .CUDAChannelFormatDesc formatDesc = 2;
inline bool CUDAArrayObject::has_formatdesc() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.formatdesc_ != nullptr);
  return value;
}
inline void CUDAArrayObject::clear_formatdesc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.formatdesc_ != nullptr) _impl_.formatdesc_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::CUDAChannelFormatDesc& CUDAArrayObject::_internal_formatdesc() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::CUDAChannelFormatDesc* p = _impl_.formatdesc_;
  return p != nullptr ? *p : reinterpret_cast<const ::CUDAChannelFormatDesc&>(::_CUDAChannelFormatDesc_default_instance_);
}
inline const ::CUDAChannelFormatDesc& CUDAArrayObject::formatdesc() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CUDAArrayObject.formatDesc)
  return _internal_formatdesc();
}
inline void CUDAArrayObject::unsafe_arena_set_allocated_formatdesc(
    ::CUDAChannelFormatDesc* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.formatdesc_);
  }
  _impl_.formatdesc_ = reinterpret_cast<::CUDAChannelFormatDesc*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CUDAArrayObject.formatDesc)
}
inline ::CUDAChannelFormatDesc* PROTOBUF_NULLABLE CUDAArrayObject::release_formatdesc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::CUDAChannelFormatDesc* released = _impl_.formatdesc_;
  _impl_.formatdesc_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::CUDAChannelFormatDesc* PROTOBUF_NULLABLE CUDAArrayObject::unsafe_arena_release_formatdesc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CUDAArrayObject.formatDesc)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::CUDAChannelFormatDesc* temp = _impl_.formatdesc_;
  _impl_.formatdesc_ = nullptr;
  return temp;
}
inline ::CUDAChannelFormatDesc* PROTOBUF_NONNULL CUDAArrayObject::_internal_mutable_formatdesc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.formatdesc_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::CUDAChannelFormatDesc>(GetArena());
    _impl_.formatdesc_ = reinterpret_cast<::CUDAChannelFormatDesc*>(p);
  }
  return _impl_.formatdesc_;
}
inline ::CUDAChannelFormatDesc* PROTOBUF_NONNULL CUDAArrayObject::mutable_formatdesc()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::CUDAChannelFormatDesc* _msg = _internal_mutable_formatdesc();
  // @@protoc_insertion_point(field_mutable:CUDAArrayObject.formatDesc)
  return _msg;
}
inline void CUDAArrayObject::set_allocated_formatdesc(::CUDAChannelFormatDesc* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.formatdesc_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.formatdesc_ = reinterpret_cast<::CUDAChannelFormatDesc*>(value);
  // @@protoc_insertion_point(field_set_allocated:CUDAArrayObject.formatDesc)
}

// optional uint64 bpp = 3;
inline bool CUDAArrayObject::has_bpp() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CUDAArrayObject::clear_bpp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bpp_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t CUDAArrayObject::bpp() const {
  // @@protoc_insertion_point(field_get:CUDAArrayObject.bpp)
  return _internal_bpp();
}
inline void CUDAArrayObject::set_bpp(::uint64_t value) {
  _internal_set_bpp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:CUDAArrayObject.bpp)
}
inline ::uint64_t CUDAArrayObject::_internal_bpp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bpp_;
}
inline void CUDAArrayObject::_internal_set_bpp(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bpp_ = value;
}

// optional uint64 pitch = 4;
inline bool CUDAArrayObject::has_pitch() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void CUDAArrayObject::clear_pitch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pitch_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t CUDAArrayObject::pitch() const {
  // @@protoc_insertion_point(field_get:CUDAArrayObject.pitch)
  return _internal_pitch();
}
inline void CUDAArrayObject::set_pitch(::uint64_t value) {
  _internal_set_pitch(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:CUDAArrayObject.pitch)
}
inline ::uint64_t CUDAArrayObject::_internal_pitch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pitch_;
}
inline void CUDAArrayObject::_internal_set_pitch(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pitch_ = value;
}

// optional .CUDAExtent extent = 5;
inline bool CUDAArrayObject::has_extent() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.extent_ != nullptr);
  return value;
}
inline void CUDAArrayObject::clear_extent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.extent_ != nullptr) _impl_.extent_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::CUDAExtent& CUDAArrayObject::_internal_extent() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::CUDAExtent* p = _impl_.extent_;
  return p != nullptr ? *p : reinterpret_cast<const ::CUDAExtent&>(::_CUDAExtent_default_instance_);
}
inline const ::CUDAExtent& CUDAArrayObject::extent() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CUDAArrayObject.extent)
  return _internal_extent();
}
inline void CUDAArrayObject::unsafe_arena_set_allocated_extent(
    ::CUDAExtent* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.extent_);
  }
  _impl_.extent_ = reinterpret_cast<::CUDAExtent*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CUDAArrayObject.extent)
}
inline ::CUDAExtent* PROTOBUF_NULLABLE CUDAArrayObject::release_extent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::CUDAExtent* released = _impl_.extent_;
  _impl_.extent_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::CUDAExtent* PROTOBUF_NULLABLE CUDAArrayObject::unsafe_arena_release_extent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CUDAArrayObject.extent)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::CUDAExtent* temp = _impl_.extent_;
  _impl_.extent_ = nullptr;
  return temp;
}
inline ::CUDAExtent* PROTOBUF_NONNULL CUDAArrayObject::_internal_mutable_extent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.extent_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::CUDAExtent>(GetArena());
    _impl_.extent_ = reinterpret_cast<::CUDAExtent*>(p);
  }
  return _impl_.extent_;
}
inline ::CUDAExtent* PROTOBUF_NONNULL CUDAArrayObject::mutable_extent()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::CUDAExtent* _msg = _internal_mutable_extent();
  // @@protoc_insertion_point(field_mutable:CUDAArrayObject.extent)
  return _msg;
}
inline void CUDAArrayObject::set_allocated_extent(::CUDAExtent* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.extent_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.extent_ = reinterpret_cast<::CUDAExtent*>(value);
  // @@protoc_insertion_point(field_set_allocated:CUDAArrayObject.extent)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // cpp_2eproto_2epb_2eh
