# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CUDAPitchedArrayObject.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'CUDAPitchedArrayObject.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CUDAChannelFormatDesc_pb2 as CUDAChannelFormatDesc__pb2
import CUDAExtent_pb2 as CUDAExtent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43UDAPitchedArrayObject.proto\x1a\x1b\x43UDAChannelFormatDesc.proto\x1a\x10\x43UDAExtent.proto\"|\n\x16\x43UDAPitchedArrayObject\x12\x0e\n\x06handle\x18\x01 \x02(\x0c\x12&\n\x06\x66ormat\x18\x02 \x02(\x0b\x32\x16.CUDAChannelFormatDesc\x12\r\n\x05pitch\x18\x03 \x02(\x04\x12\x1b\n\x06\x65xtent\x18\x04 \x02(\x0b\x32\x0b.CUDAExtent')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CUDAPitchedArrayObject_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUDAPITCHEDARRAYOBJECT']._serialized_start=79
  _globals['_CUDAPITCHEDARRAYOBJECT']._serialized_end=203
# @@protoc_insertion_point(module_scope)
