# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: VertexShaderConstants.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'VertexShaderConstants.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bVertexShaderConstants.proto\"T\n\x15VertexShaderConstants\x12\x10\n\x08nearclip\x18\x01 \x02(\x02\x12\x0f\n\x07\x66\x61rclip\x18\x02 \x02(\x02\x12\x18\n\x10\x63onstant_buffers\x18\x03 \x03(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VertexShaderConstants_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERTEXSHADERCONSTANTS']._serialized_start=31
  _globals['_VERTEXSHADERCONSTANTS']._serialized_end=115
# @@protoc_insertion_point(module_scope)
